version: '3.9'
services:
  media-uploader:
    image: media_uploader_service:latest
    container_name: media-uploader
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    networks:
      - public

networks:
  public:
    driver: bridge